#version of docker-compose
version: '3.9'

# services
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      #      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app # live reload (only works with nodemon)
      - /home/app/node_modules